issues:
  max-issues-per-linter: 0
  max-same-issues: 0
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - dupl
        - gosec
  exclude-dirs:
    - internal/valtools

linters-settings:
  errcheck:
    check-type-assertions: true
  unparam:
    check-exported: true
  unused:
    check-exported: true
  whitespace:
    multi-if: true
    multi-func: true
  errorlint:
    errorf: true
  nakedret:
    max-func-lines: 0
  gosec:
    excludes:
      - G204


run:
  timeout: 3m

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - typecheck
#    - gosec
    - unparam
    - unconvert
    - dupl
    - errorlint
    - exhaustive
    - goimports
    - nlreturn
    - whitespace
    - rowserrcheck
    - godot
    - nakedret