CFG-R001:
  description: BBI config JSON gets created
  tests:
  - INT-CFG-001
COVCOR-R001:
  description: CovCor parses .cov and .cor files
  tests:
  - INT-COVCOR-001
COVCOR-R002:
  description: CovCor errors with bad input
  tests:
  - INT-COVCOR-002
DATA-R001:
  description: Has valid data path for CTL
  tests:
  - INT-DATA-001
DATA-R002:
  description: Fails with invalid data path
  tests:
  - INT-DATA-002
DATA-R003:
  description: Has valid complex path CTL And Mod
  tests:
  - INT-DATA-003
INIT-R001:
  description: BBI can initialize
  tests:
  - INT-INIT-001
  - UNIT-INIT-001
  - UNIT-INIT-002
LOCAL-R001:
  description: BBI completes local execution
  tests:
  - INT-LOCAL-001
LOCAL-R002:
  description: NMFE options end in script
  tests:
  - INT-LOCAL-002
LOCAL-R003:
  description: BBI can execute in parallel
  tests:
  - INT-LOCAL-003
NMQ-R001:
  description: NMQUAL execution succeeds
  tests:
  - INT-NMQ-001
PARAM-R001:
  description: Parse params for single model
  tests:
  - INT-PARAM-001
PARAM-R002:
  description: Parse params for directory of models
  tests:
  - INT-PARAM-002
SGE-R001:
  description: BBI completes SGE execution
  tests:
  - INT-SGE-001
SGE-R002:
  description: BBI completes parallel SGE execution
  tests:
  - INT-SGE-002
SGE-R003:
  description: SGE execution uses same BBI executable as the main
    process by default.
  tests:
  - INT-INIT-001
  - UNIT-CMD-006
SUM-R001:
  description: BBI summary works with default settings
  tests:
  - INT-SUM-001
SUM-R002:
  description: BBI summary arguments work
  tests:
  - INT-SUM-002
SUM-R003:
  description: BBI summary fails with bad input
  tests:
  - INT-SUM-003
  - INT-SUM-006
SUM-R004:
  description: BBI summary works with no extension
  tests:
  - INT-SUM-004
SUM-R005:
  description: BBI summary reports elapsed times for each method
  tests:
  - INT-SUM-001
  - UNIT-NMP-035
SUM-R006:
  description: Correctly parse summary when OFV is NaN
  tests:
  - UNIT-NMP-019
  - INT-SUM-001
SUM-R007:
  description: BBI summary includes times that are zero
  tests:
  - INT-SUM-001
SUM-R008:
  description: Can take a list of model paths and parse summary for all models
  tests:
  - INT-SUM-005
SUM-R009:
  description: Should return a json array, with one top-level element for each
    model being summarized, in the same order they were passed in.
  tests:
  - INT-SUM-005
SUM-R010:
  description: If any of the models cannot be summarized, pass the relevant
    error back in the relevant position in the json array.
  tests:
  - INT-SUM-006
SUM-R011:
  description: Attempt to identify when a model run is incomplete or
    invalid, and report an error to the caller.
  tests:
  - INT-SUM-003
  - INT-SUM-006
SUM-R012:
  description: BBI summary includes problem_text key in JSON output
    even if lst defines $PROBLEM as an empty stirng.
  tests:
  - INT-SUM-001
CMD-R001:
  description: Process NMFE options
  tests:
  - UNIT-CMD-002
CMD-R002:
  description: Pass -maxeval=2 to NMFE by default
  tests:
  - INT-INIT-001
  - UNIT-CMD-002
NMP-R001:
  description: Parse Estimates From Ext
  tests:
  - UNIT-NMP-036
NMP-R002:
  description: Correctly parses problem text when either short or long-form
    keyword is used.
  tests:
  - UNIT-NMP-035
